export type ResourceEntry = {
  href: string;
  title: string;
  description: string;
  category: string;
  categoryLabel: string;
  updatedAt: string;
};

export const resourceEntries: ResourceEntry[] = [
  {
    href: "/resources/haccp-plan-template",
    title: "HACCP plan template",
    description: "What a practical HACCP plan should include before you turn it into a site-specific document.",
    category: "haccp",
    categoryLabel: "HACCP",
    updatedAt: "2026-03-14",
  },
  {
    href: "/resources/hazard-analysis-template",
    title: "Hazard analysis template",
    description: "What to include in a hazard analysis worksheet before you turn it into a business-specific HACCP document.",
    category: "haccp",
    categoryLabel: "HACCP",
    updatedAt: "2026-06-18",
  },
  {
    href: "/resources/corrective-action-log-template",
    title: "Corrective action log template",
    description: "How to document deviations, root causes, and actions taken to restore process control.",
    category: "haccp",
    categoryLabel: "HACCP",
    updatedAt: "2026-03-14",
  },
  {
    href: "/resources/product-recall-procedure-template",
    title: "Product recall procedure template",
    description: "The structure a recall procedure needs to enable a fast, traceable withdrawal or recall.",
    category: "haccp",
    categoryLabel: "HACCP",
    updatedAt: "2026-03-14",
  },
  {
    href: "/resources/foreign-body-poster",
    title: "Foreign body prevention poster",
    description: "A practical poster for packaging checks, utensil control, housekeeping, and other foreign-body prevention routines on EU and UK food sites.",
    category: "haccp",
    categoryLabel: "HACCP",
    updatedAt: "2026-06-20",
  },
  {
    href: "/resources/glass-brittle-poster",
    title: "Glass and brittle plastic control poster",
    description: "A visual reminder covering glass registers, brittle-plastic checks, breakage response, and segregation discipline for EU and UK food businesses.",
    category: "haccp",
    categoryLabel: "HACCP",
    updatedAt: "2026-06-20",
  },
  {
    href: "/resources/allergen-checklist-poster",
    title: "Allergen checklist poster",
    description: "A practical allergen reminder poster covering recipe changes, customer communication, and cross-contact controls for EU and UK food businesses.",
    category: "allergen",
    categoryLabel: "Allergen",
    updatedAt: "2026-06-20",
  },
  {
    href: "/resources/allergen-matrix-template",
    title: "Allergen matrix template",
    description: "How to structure allergen information so kitchen and front-of-house teams can use it.",
    category: "allergen",
    categoryLabel: "Allergen",
    updatedAt: "2026-03-14",
  },
  {
    href: "/resources/cleaning-and-disinfection-sop",
    title: "Cleaning and disinfection SOP",
    description: "How to draft a cleaning SOP that is specific enough to follow and simple enough to keep updated.",
    category: "cleaning",
    categoryLabel: "Cleaning",
    updatedAt: "2026-03-14",
  },
  {
    href: "/resources/cleaning-safety-poster",
    title: "Cleaning safety poster",
    description: "A practical poster for chemical separation, safe cleaning sequence, and contamination control in food operations.",
    category: "cleaning",
    categoryLabel: "Cleaning",
    updatedAt: "2026-07-02",
  },
  {
    href: "/resources/cooking-monitoring-log-template",
    title: "Cooking monitoring log template",
    description: "What to record for cook temperatures, batch checks, sign-off, and corrective actions when food misses its target.",
    category: "monitoring",
    categoryLabel: "Monitoring",
    updatedAt: "2026-06-18",
  },
  {
    href: "/resources/chill-chain-poster",
    title: "Chill chain poster",
    description: "A practical cold-chain reminder poster for chilled deliveries, storage discipline, date coding, and response to temperature drift.",
    category: "monitoring",
    categoryLabel: "Monitoring",
    updatedAt: "2026-07-02",
  },
  {
    href: "/resources/chilled-storage-poster",
    title: "Chilled storage checklist poster",
    description: "A chilled-storage reminder poster for temperature discipline, stock rotation, segregation, and daily fridge checks in EU and UK food operations.",
    category: "monitoring",
    categoryLabel: "Monitoring",
    updatedAt: "2026-06-20",
  },
  {
    href: "/resources/date-coding-poster",
    title: "Date coding poster",
    description: "A printable poster for opened products, prep containers, defrosted items, and stock rotation date coding discipline.",
    category: "monitoring",
    categoryLabel: "Monitoring",
    updatedAt: "2026-07-02",
  },
  {
    href: "/resources/food-temperature-poster",
    title: "Food temperature poster",
    description: "A quick-reference kitchen poster for chilled, frozen, cooking, hot-hold, cooling, and reheating temperatures.",
    category: "monitoring",
    categoryLabel: "Monitoring",
    updatedAt: "2026-06-18",
  },
  {
    href: "/resources/label-check-poster",
    title: "Label check poster",
    description: "A visual label-checking poster for allergens, date codes, storage instructions, and product identity during intake and prep.",
    category: "monitoring",
    categoryLabel: "Monitoring",
    updatedAt: "2026-07-02",
  },
  {
    href: "/resources/label-check-record-template",
    title: "Label check record template",
    description:
      "What to record when checking product labels, allergens, date codes, storage instructions, and acceptance decisions during intake and prep.",
    category: "monitoring",
    categoryLabel: "Monitoring",
    updatedAt: "2026-07-04",
  },
  {
    href: "/resources/temperature-monitoring-log-template",
    title: "Temperature monitoring log template",
    description: "What to include in fridge, freezer, hot-hold, and corrective action logs.",
    category: "monitoring",
    categoryLabel: "Monitoring",
    updatedAt: "2026-03-14",
  },
  {
    href: "/resources/food-safety-opening-and-closing-checklist",
    title: "Food safety opening and closing checklist",
    description: "A practical daily checklist structure for opening checks, closing checks, corrective actions, and shift sign-off.",
    category: "monitoring",
    categoryLabel: "Monitoring",
    updatedAt: "2026-05-22",
  },
  {
    href: "/resources/pest-control-log-template",
    title: "Pest control log template",
    description: "How to record pest activity findings, contractor visits, and remedial actions.",
    category: "monitoring",
    categoryLabel: "Monitoring",
    updatedAt: "2026-03-14",
  },
  {
    href: "/resources/hygiene-inspection-poster",
    title: "Pre-operational hygiene inspection poster",
    description: "A pre-start hygiene inspection poster covering cleanliness, setup, handwash readiness, and line-release checks for EU and UK teams.",
    category: "monitoring",
    categoryLabel: "Monitoring",
    updatedAt: "2026-06-20",
  },
  {
    href: "/resources/probe-calibration-poster",
    title: "Probe thermometer calibration poster",
    description: "A quick-reference calibration poster covering probe checks, accuracy verification, cleaning, and corrective action expectations.",
    category: "monitoring",
    categoryLabel: "Monitoring",
    updatedAt: "2026-06-20",
  },
  {
    href: "/resources/restaurant-closing-checklist",
    title: "Restaurant closing checklist",
    description: "An end-of-day restaurant checklist for storage, cleaning, waste, corrective actions, and handover across EU and UK operations.",
    category: "monitoring",
    categoryLabel: "Monitoring",
    updatedAt: "2026-06-20",
  },
  {
    href: "/resources/restaurant-opening-checklist",
    title: "Restaurant opening checklist",
    description: "A pre-service restaurant checklist covering hygiene, temperatures, allergen readiness, and equipment checks for EU and UK teams.",
    category: "monitoring",
    categoryLabel: "Monitoring",
    updatedAt: "2026-06-20",
  },
  {
    href: "/resources/restaurant-opening-poster",
    title: "Restaurant opening poster",
    description: "A visual pre-service reminder poster for restaurant hygiene, temperatures, allergen checks, and opening readiness.",
    category: "monitoring",
    categoryLabel: "Monitoring",
    updatedAt: "2026-06-20",
  },
  {
    href: "/resources/waste-management-log-template",
    title: "Waste management log template",
    description: "A structure for recording food waste disposal, condemned stock, and waste contractor details.",
    category: "monitoring",
    categoryLabel: "Monitoring",
    updatedAt: "2026-03-14",
  },
  {
    href: "/resources/waste-management-sop-template",
    title: "Waste management SOP template",
    description: "How to write a waste management procedure covering segregation, storage, contractor arrangements, and compliance.",
    category: "monitoring",
    categoryLabel: "Monitoring",
    updatedAt: "2026-03-14",
  },
  {
    href: "/resources/traceability-log-template",
    title: "Traceability log template",
    description: "What one-step-back, one-step-forward traceability records should capture for EU and UK compliance.",
    category: "traceability",
    categoryLabel: "Traceability",
    updatedAt: "2026-03-14",
  },
  {
    href: "/resources/traceability-recall-poster",
    title: "Traceability and recall readiness poster",
    description: "A practical poster for batch identification, lot linking, withdrawal triggers, and recall-readiness discipline in EU and UK food businesses.",
    category: "traceability",
    categoryLabel: "Traceability",
    updatedAt: "2026-06-20",
  },
  {
    href: "/resources/supplier-approval-questionnaire",
    title: "Supplier approval questionnaire",
    description: "Questions and evidence points food businesses use when approving or re-approving suppliers.",
    category: "supplier",
    categoryLabel: "Supplier",
    updatedAt: "2026-03-14",
  },
  {
    href: "/resources/food-spec-template",
    title: "Food specification template",
    description:
      "A structured product specification template covering composition, allergens, storage, shelf life, and supplier approval details.",
    category: "supplier",
    categoryLabel: "Supplier",
    updatedAt: "2026-06-23",
  },
  {
    href: "/resources/supplier-registration-log",
    title: "Supplier registration log",
    description: "A supplier tracker for approval status, review dates, product scope, and due-diligence follow-up.",
    category: "supplier",
    categoryLabel: "Supplier",
    updatedAt: "2026-06-18",
  },
  {
    href: "/resources/supplier-approval-poster",
    title: "Supplier approval checklist poster",
    description: "A visual supplier-approval poster covering due diligence, product scope, review dates, and escalation points for EU and UK food businesses.",
    category: "supplier",
    categoryLabel: "Supplier",
    updatedAt: "2026-06-20",
  },
  {
    href: "/resources/employee-food-safety-training-record",
    title: "Employee food safety training record",
    description: "What training records should capture to demonstrate staff competence during inspections.",
    category: "training",
    categoryLabel: "Training",
    updatedAt: "2026-03-14",
  },
  {
    href: "/resources/gmp-poster",
    title: "GMP poster",
    description: "A visual good manufacturing practice poster covering hygiene, handling, contamination control, and daily discipline on site.",
    category: "training",
    categoryLabel: "Training",
    updatedAt: "2026-06-18",
  },
  {
    href: "/resources/food-safety-culture-poster",
    title: "Food safety culture poster",
    description: "A food safety culture poster reinforcing ownership, escalation, communication, and day-to-day food safety behaviours across EU and UK teams.",
    category: "training",
    categoryLabel: "Training",
    updatedAt: "2026-06-20",
  },
  {
    href: "/resources/halal-compliance-poster",
    title: "Halal compliance poster",
    description: "A visual operational reminder for halal-sensitive sourcing, segregation, ingredient checks, and staff handling discipline.",
    category: "training",
    categoryLabel: "Training",
    updatedAt: "2026-06-20",
  },
  {
    href: "/resources/kosher-compliance-poster",
    title: "Kosher compliance poster",
    description: "A visual operational reminder for kosher-sensitive ingredient checks, segregation, equipment awareness, and handling discipline.",
    category: "training",
    categoryLabel: "Training",
    updatedAt: "2026-06-20",
  },
  {
    href: "/resources/handwashing-poster",
    title: "Handwashing poster",
    description: "A printable kitchen handwashing poster that reinforces the critical moments and sequence for staff hygiene on site.",
    category: "training",
    categoryLabel: "Training",
    updatedAt: "2026-07-02",
  },
  {
    href: "/resources/personal-hygiene-policy-template",
    title: "Personal hygiene policy template",
    description: "The key elements a staff hygiene policy should cover to be enforceable and inspection-ready.",
    category: "training",
    categoryLabel: "Training",
    updatedAt: "2026-03-14",
  },
  {
    href: "/resources/personal-hygiene-poster",
    title: "Personal hygiene checklist poster",
    description: "A practical hygiene checklist poster covering handwashing, illness reporting, protective clothing, and behaviour rules for EU and UK food teams.",
    category: "training",
    categoryLabel: "Training",
    updatedAt: "2026-06-20",
  },
  {
    href: "/resources/incoming-goods-template",
    title: "Incoming goods inspection template",
    description: "What to record when goods arrive - supplier, product, quantity, condition, and temperature - to maintain traceability from the point of receipt.",
    category: "traceability",
    categoryLabel: "Traceability",
    updatedAt: "2026-05-22",
  },
  {
    href: "/resources/customer-complaint-log-template",
    title: "Customer complaint log template",
    description: "How to record, investigate, and close customer complaints in a way that feeds back into your HACCP and corrective action process.",
    category: "haccp",
    categoryLabel: "HACCP",
    updatedAt: "2026-05-22",
  },
  {
    href: "/resources/equipment-calibration-log-template",
    title: "Equipment calibration log template",
    description: "What calibration records should capture for probes, scales, and other critical measuring equipment used in food safety monitoring.",
    category: "monitoring",
    categoryLabel: "Monitoring",
    updatedAt: "2026-05-22",
  },
  {
    href: "/resources/food-safety-audit-checklist",
    title: "Food safety audit checklist",
    description: "A practical structure for monthly internal review and inspection preparation.",
    category: "haccp",
    categoryLabel: "HACCP",
    updatedAt: "2026-03-14",
  },
  {
    href: "/resources/brc-checklist-poster",
    title: "BRC checklist poster",
    description: "A printable poster for visible BRC-style site standards around hygiene, housekeeping, segregation, records, and audit-readiness.",
    category: "haccp",
    categoryLabel: "HACCP",
    updatedAt: "2026-07-05",
  },
  {
    href: "/resources/food-safety-document-checklist",
    title: "EU and UK document checklist",
    description: "A document checklist covering the policies, logs, and supporting evidence food businesses are commonly asked to produce.",
    category: "haccp",
    categoryLabel: "HACCP",
    updatedAt: "2026-03-14",
  },
  {
    href: "/resources/food-safety-management-system-template",
    title: "Food safety management system template",
    description: "A structured starting point for documenting the policies, procedures, and records behind a usable food safety management system.",
    category: "haccp",
    categoryLabel: "HACCP",
    updatedAt: "2026-03-14",
  },
  {
    href: "/resources/iso22000-checklist-poster",
    title: "ISO 22000 checklist poster",
    description: "A printable poster for ISO 22000-style system discipline across prerequisite programmes, monitoring, records, and review routines.",
    category: "haccp",
    categoryLabel: "HACCP",
    updatedAt: "2026-07-05",
  },
  {
    href: "/resources/workplace-compliance-poster",
    title: "Workplace compliance poster",
    description: "A visual workplace poster for hygiene, conduct, clothing, reporting discipline, and safe handling expectations on site.",
    category: "training",
    categoryLabel: "Training",
    updatedAt: "2026-07-05",
  },
];

export const featuredResourceHrefs = [
  "/resources/haccp-plan-template",
  "/resources/allergen-matrix-template",
  "/resources/food-spec-template",
  "/resources/food-safety-opening-and-closing-checklist",
  "/resources/temperature-monitoring-log-template",
] as const;

export function getFeaturedResources() {
  return resourceEntries.filter((resource) =>
    featuredResourceHrefs.includes(resource.href as (typeof featuredResourceHrefs)[number]),
  );
}
