/**
 * Renders structured document data into professional PDF files using pdf-lib.
 */

import { PDFDocument, StandardFonts, rgb, PDFFont, PDFPage } from "pdf-lib";
import type {
  StructuredDocument,
  HACCPPlanData,
  SOPData,
  CleaningScheduleData,
  TemperatureLogData,
  SupplierApprovalData,
} from "./types";
import { DOCUMENT_TYPE_LABELS } from "./types";

const PAGE_WIDTH = 841.89; // A4 landscape for tables
const PAGE_HEIGHT = 595.28;
const MARGIN = 40;
const CONTENT_WIDTH = PAGE_WIDTH - 2 * MARGIN;

type RenderContext = {
  doc: PDFDocument;
  font: PDFFont;
  bold: PDFFont;
  page: PDFPage;
  y: number;
};

function newPage(ctx: RenderContext): void {
  ctx.page = ctx.doc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);
  ctx.y = PAGE_HEIGHT - MARGIN;
}

function ensureSpace(ctx: RenderContext, needed: number): void {
  if (ctx.y - needed < MARGIN) {
    newPage(ctx);
  }
}

function drawTitle(ctx: RenderContext, text: string): void {
  ensureSpace(ctx, 30);
  ctx.page.drawText(text, { x: MARGIN, y: ctx.y, size: 18, font: ctx.bold, color: rgb(0.88, 0.11, 0.28) });
  ctx.y -= 28;
}

function drawHeading(ctx: RenderContext, text: string): void {
  ensureSpace(ctx, 24);
  ctx.y -= 8;
  ctx.page.drawText(text, { x: MARGIN, y: ctx.y, size: 13, font: ctx.bold, color: rgb(0.06, 0.09, 0.16) });
  ctx.y -= 20;
}

function drawText(ctx: RenderContext, text: string, x = MARGIN, size = 10): void {
  ensureSpace(ctx, 14);
  // Word wrap
  const maxWidth = PAGE_WIDTH - x - MARGIN;
  const words = text.split(/\s+/);
  let line = "";
  for (const word of words) {
    const test = line ? `${line} ${word}` : word;
    const width = ctx.font.widthOfTextAtSize(test, size);
    if (width > maxWidth && line) {
      ctx.page.drawText(line, { x, y: ctx.y, size, font: ctx.font, color: rgb(0.06, 0.09, 0.16) });
      ctx.y -= 14;
      ensureSpace(ctx, 14);
      line = word;
    } else {
      line = test;
    }
  }
  if (line) {
    ctx.page.drawText(line, { x, y: ctx.y, size, font: ctx.font, color: rgb(0.06, 0.09, 0.16) });
    ctx.y -= 14;
  }
}

function drawMeta(ctx: RenderContext, doc: { version: string; date: string; business_name: string; approved_by?: string }): void {
  drawText(ctx, `Business: ${doc.business_name}`);
  drawText(ctx, `Version: ${doc.version}  |  Date: ${doc.date}  |  Approved by: ${doc.approved_by || "________________________"}`);
  drawText(ctx, "AI-assisted draft generated by PinkPepper. Human validation required before operational use.");
  ctx.y -= 10;
  // Separator line
  ctx.page.drawLine({
    start: { x: MARGIN, y: ctx.y },
    end: { x: PAGE_WIDTH - MARGIN, y: ctx.y },
    thickness: 0.5,
    color: rgb(0.89, 0.91, 0.94),
  });
  ctx.y -= 16;
}

function drawTable(ctx: RenderContext, headers: string[], rows: string[][], colWidths?: number[]): void {
  const cols = headers.length;
  const defaultW = CONTENT_WIDTH / cols;
  const widths = colWidths ?? headers.map(() => defaultW);
  const rowHeight = 16;
  const cellPad = 4;
  const fontSize = 8;

  // Header
  ensureSpace(ctx, rowHeight + 4);
  let x = MARGIN;
  for (let i = 0; i < cols; i++) {
    // Header background
    ctx.page.drawRectangle({
      x,
      y: ctx.y - rowHeight + 4,
      width: widths[i],
      height: rowHeight,
      color: rgb(0.99, 0.95, 0.95),
    });
    const truncated = headers[i].substring(0, Math.floor(widths[i] / (fontSize * 0.5)));
    ctx.page.drawText(truncated, {
      x: x + cellPad,
      y: ctx.y - rowHeight + 8,
      size: fontSize,
      font: ctx.bold,
      color: rgb(0.06, 0.09, 0.16),
    });
    x += widths[i];
  }
  ctx.y -= rowHeight + 2;

  // Rows
  for (const row of rows) {
    ensureSpace(ctx, rowHeight + 2);
    x = MARGIN;
    for (let i = 0; i < cols; i++) {
      const cellText = (row[i] ?? "").substring(0, Math.floor(widths[i] / (fontSize * 0.45)));
      ctx.page.drawText(cellText, {
        x: x + cellPad,
        y: ctx.y - rowHeight + 8,
        size: fontSize,
        font: ctx.font,
        color: rgb(0.06, 0.09, 0.16),
      });
      x += widths[i];
    }
    // Row separator
    ctx.page.drawLine({
      start: { x: MARGIN, y: ctx.y - rowHeight + 2 },
      end: { x: PAGE_WIDTH - MARGIN, y: ctx.y - rowHeight + 2 },
      thickness: 0.3,
      color: rgb(0.89, 0.91, 0.94),
    });
    ctx.y -= rowHeight;
  }
  ctx.y -= 8;
}

// ============================================================
// Document type renderers
// ============================================================

function renderHACCP(ctx: RenderContext, data: HACCPPlanData): void {
  drawTitle(ctx, "HACCP Plan");
  drawMeta(ctx, data);

  drawHeading(ctx, "1. Product Description");
  drawText(ctx, `Product: ${data.product_description}`);
  drawText(ctx, `Intended use: ${data.intended_use}`);
  if (data.target_consumer) drawText(ctx, `Target consumer: ${data.target_consumer}`);

  if (data.prerequisite_programmes?.length) {
    drawHeading(ctx, "2. Prerequisite Programmes");
    for (const p of data.prerequisite_programmes) {
      drawText(ctx, `• ${p}`);
    }
  }

  drawHeading(ctx, "3. Hazard Analysis");
  drawTable(
    ctx,
    ["Step", "Hazard", "Type", "Control Measure", "Monitoring"],
    data.process_steps.map((s) => [s.step, s.hazard, s.hazard_type, s.control_measure, s.monitoring]),
  );

  drawHeading(ctx, "4. Critical Control Points");
  const ccpWidths = [30, 80, 80, 70, 90, 70, 100, 90, 90].map((w) => (w / 700) * CONTENT_WIDTH);
  drawTable(
    ctx,
    ["#", "CCP", "Hazard", "Limit", "Monitor", "Freq", "Corrective", "Verify", "Records"],
    data.ccps.map((c) => [
      String(c.ccp_number),
      c.name,
      c.hazard,
      c.critical_limit,
      c.monitoring_procedure,
      c.monitoring_frequency,
      c.corrective_action,
      c.verification,
      c.records,
    ]),
    ccpWidths,
  );

  if (data.review_frequency) {
    drawHeading(ctx, "5. Review");
    drawText(ctx, `Review frequency: ${data.review_frequency}`);
  }
}

function renderSOPPdf(ctx: RenderContext, data: SOPData): void {
  drawTitle(ctx, data.title);
  drawMeta(ctx, data);
  drawHeading(ctx, "Purpose");
  drawText(ctx, data.purpose);
  drawHeading(ctx, "Scope");
  drawText(ctx, data.scope);
  drawHeading(ctx, "Responsibilities");
  for (const r of data.responsibilities) drawText(ctx, `• ${r}`);
  drawHeading(ctx, "Procedure");
  for (const s of data.steps) {
    drawText(ctx, `${s.step_number}. ${s.action}`);
    drawText(ctx, `   ${s.details}`, MARGIN + 16);
  }
  if (data.monitoring) { drawHeading(ctx, "Monitoring"); drawText(ctx, data.monitoring); }
  if (data.corrective_actions) { drawHeading(ctx, "Corrective Actions"); drawText(ctx, data.corrective_actions); }
  if (data.references?.length) {
    drawHeading(ctx, "References");
    for (const ref of data.references) drawText(ctx, `• ${ref}`);
  }
}

function renderCleaningPdf(ctx: RenderContext, data: CleaningScheduleData): void {
  drawTitle(ctx, "Cleaning Schedule");
  drawMeta(ctx, data);
  drawTable(
    ctx,
    ["Area", "Task", "Frequency", "Method", "Chemical", "Conc.", "Time", "Responsible"],
    data.entries.map((e) => [e.area, e.task, e.frequency, e.method, e.chemical, e.concentration, e.contact_time, e.responsible]),
  );
}

function renderTempLogPdf(ctx: RenderContext, data: TemperatureLogData): void {
  drawTitle(ctx, "Temperature Monitoring Log");
  drawMeta(ctx, data);
  drawTable(
    ctx,
    ["Location", "Equipment", "Target", "Range", "Frequency", "Corrective Action"],
    data.columns.map((c) => [c.location, c.equipment, c.target_temp, c.acceptable_range, c.frequency, c.corrective_action]),
  );
}

function renderSupplierPdf(ctx: RenderContext, data: SupplierApprovalData): void {
  drawTitle(ctx, "Approved Supplier List");
  drawMeta(ctx, data);
  if (data.approval_criteria?.length) {
    drawHeading(ctx, "Approval Criteria");
    for (const c of data.approval_criteria) drawText(ctx, `• ${c}`);
  }
  drawTable(
    ctx,
    ["Supplier", "Products", "Status", "Last Audit", "Certificates", "Next Review"],
    data.suppliers.map((s) => [s.supplier_name, s.products_supplied, s.approval_status, s.last_audit_date ?? "—", s.certificates_held ?? "—", s.next_review_date ?? "—"]),
  );
}

// ============================================================
// Public API
// ============================================================

/**
 * Render a structured document into a PDF buffer.
 */
export async function renderPdf(data: StructuredDocument): Promise<Uint8Array> {
  const pdfDoc = await PDFDocument.create();
  const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
  const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);
  const page = pdfDoc.addPage([PAGE_WIDTH, PAGE_HEIGHT]);

  const ctx: RenderContext = { doc: pdfDoc, font, bold, page, y: PAGE_HEIGHT - MARGIN };

  switch (data.document_type) {
    case "haccp_plan":
      renderHACCP(ctx, data);
      break;
    case "sop":
      renderSOPPdf(ctx, data);
      break;
    case "cleaning_schedule":
      renderCleaningPdf(ctx, data);
      break;
    case "temperature_log":
      renderTempLogPdf(ctx, data);
      break;
    case "supplier_approval":
      renderSupplierPdf(ctx, data);
      break;
  }

  return pdfDoc.save();
}
