/**
 * Renders structured document data into professional DOCX files using the `docx` library.
 * Templates are code-defined for maximum control over formatting.
 */

import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  Table,
  TableRow,
  TableCell,
  HeadingLevel,
  AlignmentType,
  WidthType,
  BorderStyle,
  ShadingType,
} from "docx";
import type {
  StructuredDocument,
  HACCPPlanData,
  SOPData,
  CleaningScheduleData,
  TemperatureLogData,
  SupplierApprovalData,
} from "./types";
import { DOCUMENT_TYPE_LABELS } from "./types";

// ============================================================
// Shared helpers
// ============================================================

const BRAND_COLOR = "E11D48";
const HEADER_BG = "FEF2F2";
const FONT = "Calibri";

function headerCell(text: string, width?: number): TableCell {
  return new TableCell({
    children: [
      new Paragraph({
        children: [new TextRun({ text, bold: true, font: FONT, size: 20, color: "0F172A" })],
        alignment: AlignmentType.LEFT,
      }),
    ],
    shading: { type: ShadingType.SOLID, color: HEADER_BG },
    width: width ? { size: width, type: WidthType.PERCENTAGE } : undefined,
  });
}

function cell(text: string, width?: number): TableCell {
  return new TableCell({
    children: [
      new Paragraph({
        children: [new TextRun({ text, font: FONT, size: 20 })],
      }),
    ],
    width: width ? { size: width, type: WidthType.PERCENTAGE } : undefined,
  });
}

function heading(text: string, level: (typeof HeadingLevel)[keyof typeof HeadingLevel] = HeadingLevel.HEADING_2): Paragraph {
  return new Paragraph({
    heading: level,
    children: [new TextRun({ text, font: FONT, color: "0F172A" })],
    spacing: { before: 240, after: 120 },
  });
}

function bodyText(text: string): Paragraph {
  return new Paragraph({
    children: [new TextRun({ text, font: FONT, size: 22 })],
    spacing: { after: 120 },
  });
}

function versionBlock(doc: { version: string; date: string; business_name: string; approved_by?: string }, title: string): Paragraph[] {
  return [
    new Paragraph({
      heading: HeadingLevel.TITLE,
      children: [new TextRun({ text: title, font: FONT, color: BRAND_COLOR })],
    }),
    new Paragraph({
      children: [
        new TextRun({ text: `Business: `, bold: true, font: FONT, size: 22 }),
        new TextRun({ text: doc.business_name, font: FONT, size: 22 }),
      ],
    }),
    new Paragraph({
      children: [
        new TextRun({ text: `Document No.: `, bold: true, font: FONT, size: 20 }),
        new TextRun({ text: `PP-${doc.date.replace(/-/g, "")}-001`, font: FONT, size: 20 }),
        new TextRun({ text: `   Version: `, bold: true, font: FONT, size: 20 }),
        new TextRun({ text: doc.version, font: FONT, size: 20 }),
        new TextRun({ text: `   Date: `, bold: true, font: FONT, size: 20 }),
        new TextRun({ text: doc.date, font: FONT, size: 20 }),
      ],
    }),
    new Paragraph({
      children: [
        new TextRun({ text: `Approved by: `, bold: true, font: FONT, size: 20 }),
        new TextRun({ text: doc.approved_by || "________________________", font: FONT, size: 20 }),
      ],
      spacing: { after: 200 },
    }),
    new Paragraph({
      children: [
        new TextRun({
          text: "AI-assisted draft generated by PinkPepper. Human validation required before operational use.",
          font: FONT,
          size: 18,
          italics: true,
          color: "64748B",
        }),
      ],
      spacing: { after: 300 },
      border: {
        bottom: { style: BorderStyle.SINGLE, size: 1, color: "E2E8F0" },
      },
    }),
  ];
}

// ============================================================
// HACCP Plan renderer
// ============================================================

function renderHACCPPlan(data: HACCPPlanData): Paragraph[] {
  const elements: Paragraph[] = [];

  elements.push(
    ...versionBlock(data, "HACCP Plan"),
    heading("1. Product Description"),
    bodyText(`Product: ${data.product_description}`),
    bodyText(`Intended use: ${data.intended_use}`),
  );

  if (data.target_consumer) {
    elements.push(bodyText(`Target consumer: ${data.target_consumer}`));
  }

  // Prerequisite programmes
  if (data.prerequisite_programmes?.length) {
    elements.push(heading("2. Prerequisite Programmes"));
    for (const prp of data.prerequisite_programmes) {
      elements.push(bodyText(`• ${prp}`));
    }
  }

  // Hazard analysis table
  elements.push(heading("3. Hazard Analysis"));

  const haRows = [
    new TableRow({
      tableHeader: true,
      children: [headerCell("Step"), headerCell("Hazard"), headerCell("Type"), headerCell("Control Measure"), headerCell("Monitoring")],
    }),
    ...data.process_steps.map(
      (s) =>
        new TableRow({
          children: [cell(s.step), cell(s.hazard), cell(s.hazard_type), cell(s.control_measure), cell(s.monitoring)],
        })
    ),
  ];

  elements.push(
    new Paragraph({ children: [] }), // spacer
  );

  // CCP table
  elements.push(heading("4. Critical Control Points"));

  const ccpRows = [
    new TableRow({
      tableHeader: true,
      children: [
        headerCell("CCP #"),
        headerCell("Name"),
        headerCell("Hazard"),
        headerCell("Critical Limit"),
        headerCell("Monitoring"),
        headerCell("Frequency"),
        headerCell("Corrective Action"),
        headerCell("Verification"),
        headerCell("Records"),
      ],
    }),
    ...data.ccps.map(
      (c) =>
        new TableRow({
          children: [
            cell(String(c.ccp_number)),
            cell(c.name),
            cell(c.hazard),
            cell(c.critical_limit),
            cell(c.monitoring_procedure),
            cell(c.monitoring_frequency),
            cell(c.corrective_action),
            cell(c.verification),
            cell(c.records),
          ],
        })
    ),
  ];

  if (data.review_frequency) {
    elements.push(heading("5. Review"));
    elements.push(bodyText(`Review frequency: ${data.review_frequency}`));
  }

  // We need to return paragraphs and tables interspersed. Since Document sections
  // accept (Paragraph | Table)[], we'll cast via a helper.
  // For now, embed tables as separate items by returning a flat array.
  return elements;
}

// ============================================================
// SOP renderer
// ============================================================

function renderSOP(data: SOPData): Paragraph[] {
  const elements: Paragraph[] = [
    ...versionBlock(data, data.title),
    heading("Purpose"),
    bodyText(data.purpose),
    heading("Scope"),
    bodyText(data.scope),
    heading("Responsibilities"),
    ...data.responsibilities.map((r) => bodyText(`• ${r}`)),
  ];

  if (data.equipment_materials?.length) {
    elements.push(heading("Equipment & Materials"));
    for (const item of data.equipment_materials) {
      elements.push(bodyText(`• ${item}`));
    }
  }

  elements.push(heading("Procedure"));
  for (const step of data.steps) {
    elements.push(
      new Paragraph({
        children: [
          new TextRun({ text: `${step.step_number}. ${step.action}`, bold: true, font: FONT, size: 22 }),
        ],
        spacing: { before: 120 },
      }),
      bodyText(step.details),
    );
    if (step.responsible) {
      elements.push(bodyText(`   Responsible: ${step.responsible}`));
    }
  }

  if (data.monitoring) {
    elements.push(heading("Monitoring"), bodyText(data.monitoring));
  }
  if (data.corrective_actions) {
    elements.push(heading("Corrective Actions"), bodyText(data.corrective_actions));
  }
  if (data.records?.length) {
    elements.push(heading("Records"));
    for (const rec of data.records) {
      elements.push(bodyText(`• ${rec}`));
    }
  }
  if (data.references?.length) {
    elements.push(heading("References"));
    for (const ref of data.references) {
      elements.push(bodyText(`• ${ref}`));
    }
  }

  return elements;
}

// ============================================================
// Cleaning Schedule renderer
// ============================================================

function renderCleaningSchedule(data: CleaningScheduleData): Paragraph[] {
  return [
    ...versionBlock(data, "Cleaning Schedule"),
    heading("Cleaning Tasks"),
  ];
}

// ============================================================
// Temperature Log renderer
// ============================================================

function renderTemperatureLog(data: TemperatureLogData): Paragraph[] {
  return [
    ...versionBlock(data, "Temperature Monitoring Log"),
    heading("Monitoring Points"),
  ];
}

// ============================================================
// Supplier Approval renderer
// ============================================================

function renderSupplierApproval(data: SupplierApprovalData): Paragraph[] {
  const elements = [
    ...versionBlock(data, "Approved Supplier List"),
  ];

  if (data.approval_criteria?.length) {
    elements.push(heading("Approval Criteria"));
    for (const c of data.approval_criteria) {
      elements.push(bodyText(`• ${c}`));
    }
  }

  elements.push(heading("Supplier Register"));
  return elements;
}

// ============================================================
// Table builders (separate because Document sections accept Paragraph | Table)
// ============================================================

function buildHACCPTables(data: HACCPPlanData): Table[] {
  const tables: Table[] = [];

  // Hazard analysis table
  tables.push(
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        new TableRow({
          tableHeader: true,
          children: [headerCell("Step", 20), headerCell("Hazard", 20), headerCell("Type", 12), headerCell("Control", 24), headerCell("Monitoring", 24)],
        }),
        ...data.process_steps.map(
          (s) =>
            new TableRow({
              children: [cell(s.step, 20), cell(s.hazard, 20), cell(s.hazard_type, 12), cell(s.control_measure, 24), cell(s.monitoring, 24)],
            })
        ),
      ],
    })
  );

  // CCP table
  tables.push(
    new Table({
      width: { size: 100, type: WidthType.PERCENTAGE },
      rows: [
        new TableRow({
          tableHeader: true,
          children: [
            headerCell("#", 5),
            headerCell("CCP", 12),
            headerCell("Hazard", 12),
            headerCell("Limit", 10),
            headerCell("Monitor", 13),
            headerCell("Freq", 10),
            headerCell("Corrective", 13),
            headerCell("Verify", 12),
            headerCell("Records", 13),
          ],
        }),
        ...data.ccps.map(
          (c) =>
            new TableRow({
              children: [
                cell(String(c.ccp_number), 5),
                cell(c.name, 12),
                cell(c.hazard, 12),
                cell(c.critical_limit, 10),
                cell(c.monitoring_procedure, 13),
                cell(c.monitoring_frequency, 10),
                cell(c.corrective_action, 13),
                cell(c.verification, 12),
                cell(c.records, 13),
              ],
            })
        ),
      ],
    })
  );

  return tables;
}

function buildCleaningTable(data: CleaningScheduleData): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        tableHeader: true,
        children: [
          headerCell("Area"),
          headerCell("Task"),
          headerCell("Frequency"),
          headerCell("Method"),
          headerCell("Chemical"),
          headerCell("Concentration"),
          headerCell("Contact Time"),
          headerCell("Responsible"),
        ],
      }),
      ...data.entries.map(
        (e) =>
          new TableRow({
            children: [
              cell(e.area),
              cell(e.task),
              cell(e.frequency),
              cell(e.method),
              cell(e.chemical),
              cell(e.concentration),
              cell(e.contact_time),
              cell(e.responsible),
            ],
          })
      ),
    ],
  });
}

function buildTemperatureTable(data: TemperatureLogData): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        tableHeader: true,
        children: [
          headerCell("Location"),
          headerCell("Equipment"),
          headerCell("Target"),
          headerCell("Range"),
          headerCell("Frequency"),
          headerCell("Corrective Action"),
        ],
      }),
      ...data.columns.map(
        (c) =>
          new TableRow({
            children: [
              cell(c.location),
              cell(c.equipment),
              cell(c.target_temp),
              cell(c.acceptable_range),
              cell(c.frequency),
              cell(c.corrective_action),
            ],
          })
      ),
    ],
  });
}

function buildSupplierTable(data: SupplierApprovalData): Table {
  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      new TableRow({
        tableHeader: true,
        children: [
          headerCell("Supplier"),
          headerCell("Products"),
          headerCell("Status"),
          headerCell("Last Audit"),
          headerCell("Certificates"),
          headerCell("Next Review"),
        ],
      }),
      ...data.suppliers.map(
        (s) =>
          new TableRow({
            children: [
              cell(s.supplier_name),
              cell(s.products_supplied),
              cell(s.approval_status),
              cell(s.last_audit_date ?? "—"),
              cell(s.certificates_held ?? "—"),
              cell(s.next_review_date ?? "—"),
            ],
          })
      ),
    ],
  });
}

// ============================================================
// Public API
// ============================================================

type SectionChild = Paragraph | Table;

function buildSectionChildren(doc: StructuredDocument): SectionChild[] {
  switch (doc.document_type) {
    case "haccp_plan": {
      const paragraphs = renderHACCPPlan(doc);
      const tables = buildHACCPTables(doc);
      // Insert tables after relevant headings
      const children: SectionChild[] = [];
      let haHeadingSeen = false;
      let ccpHeadingSeen = false;
      for (const p of paragraphs) {
        children.push(p);
        // Check if this paragraph contains "Hazard Analysis" heading
        if (!haHeadingSeen && p instanceof Paragraph) {
          const text = (p as unknown as { root?: unknown[] })?.constructor?.name;
          // Simple approach: insert table after hazard analysis heading
          const pText = JSON.stringify(p);
          if (pText.includes("Hazard Analysis")) {
            haHeadingSeen = true;
            if (tables[0]) children.push(tables[0]);
          }
          if (pText.includes("Critical Control Points")) {
            ccpHeadingSeen = true;
            if (tables[1]) children.push(tables[1]);
          }
        }
      }
      // Fallback: append tables at end if not inserted
      if (!haHeadingSeen && tables[0]) children.push(tables[0]);
      if (!ccpHeadingSeen && tables[1]) children.push(tables[1]);
      return children;
    }
    case "sop":
      return renderSOP(doc);
    case "cleaning_schedule":
      return [...renderCleaningSchedule(doc), buildCleaningTable(doc)];
    case "temperature_log":
      return [...renderTemperatureLog(doc), buildTemperatureTable(doc)];
    case "supplier_approval":
      return [...renderSupplierApproval(doc), buildSupplierTable(doc)];
  }
}

/**
 * Render a structured document into a DOCX buffer.
 */
export async function renderDocx(doc: StructuredDocument): Promise<Buffer> {
  const children = buildSectionChildren(doc);

  const document = new Document({
    sections: [
      {
        properties: {
          page: {
            margin: { top: 720, right: 720, bottom: 720, left: 720 },
          },
        },
        children,
      },
    ],
  });

  const buffer = await Packer.toBuffer(document);
  return Buffer.from(buffer);
}
