import {
  Document,
  Packer,
  Paragraph,
  TextRun,
  ImageRun,
  HeadingLevel,
  Table,
  TableRow,
  TableCell,
  WidthType,
  BorderStyle,
  AlignmentType,
  ShadingType,
  Header,
  Footer,
  PageNumber,
} from "docx";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import type { GeneratedDocument, DocumentTable } from "./types";
import { renderHaccpDocx } from "./render-haccp-docx";

const BRAND_COLOR = "E11D48"; // PinkPepper red
const GRAY_COLOR = "64748B";
const ALT_ROW_COLOR = "F1F5F9";

let cachedLogoBuffer: Buffer | null = null;

async function loadLogoBuffer(): Promise<Buffer | null> {
  if (cachedLogoBuffer) return cachedLogoBuffer;
  try {
    const logoPath = join(process.cwd(), "public", "LogoV3.png");
    cachedLogoBuffer = await readFile(logoPath) as Buffer;
    return cachedLogoBuffer;
  } catch {
    return null;
  }
}

function metaRow(label: string, value: string): Paragraph {
  return new Paragraph({
    children: [
      new TextRun({ text: `${label}: `, bold: true, size: 20 }),
      new TextRun({ text: value, size: 20 }),
    ],
    spacing: { after: 60 },
  });
}

function renderTable(table: DocumentTable): Table {
  const headerRow = new TableRow({
    tableHeader: true,
    children: table.columns.map(
      (col) =>
        new TableCell({
          children: [
            new Paragraph({
              children: [new TextRun({ text: col.header, bold: true, color: "FFFFFF", size: 18 })],
              alignment: AlignmentType.CENTER,
            }),
          ],
          shading: { type: ShadingType.SOLID, color: BRAND_COLOR },
        })
    ),
  });

  const dataRows = table.rows.map(
    (row: Record<string, string>, ri: number) =>
      new TableRow({
        children: table.columns.map(
          (col) =>
            new TableCell({
              children: [
                new Paragraph({
                  children: [new TextRun({ text: row[col.header] ?? "", size: 18 })],
                }),
              ],
              shading: ri % 2 === 1 ? { type: ShadingType.SOLID, color: ALT_ROW_COLOR } : undefined,
            })
        ),
      })
  );

  const borderOpts = { style: BorderStyle.SINGLE, size: 1, color: "E2E8F0" };

  return new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    borders: {
      top: borderOpts,
      bottom: borderOpts,
      left: borderOpts,
      right: borderOpts,
    },
    rows: [headerRow, ...dataRows],
  });
}

export async function renderDocx(doc: GeneratedDocument): Promise<ArrayBuffer> {
  if (doc.documentType === "haccp_plan" && doc.haccpData) {
    return renderHaccpDocx(doc.haccpData);
  }

  const logoBuffer = await loadLogoBuffer();

  const headerChildren: (TextRun | ImageRun)[] = [];
  if (logoBuffer) {
    headerChildren.push(
      new ImageRun({
        data: logoBuffer,
        transformation: { width: 120, height: 32 },
        type: "png",
      })
    );
    headerChildren.push(
      new TextRun({ text: "  |  Food Safety Compliance", color: GRAY_COLOR, size: 16 })
    );
  } else {
    headerChildren.push(
      new TextRun({ text: "PinkPepper", bold: true, color: BRAND_COLOR, size: 20 })
    );
    headerChildren.push(
      new TextRun({ text: "  |  Food Safety Compliance", color: GRAY_COLOR, size: 16 })
    );
  }

  const children: (Paragraph | Table)[] = [
    // Title
    new Paragraph({
      text: doc.title,
      heading: HeadingLevel.TITLE,
      spacing: { after: 200 },
      style: "Title",
    }),

    // Metadata block
    metaRow("Document No.", doc.documentNumber),
    metaRow("Version", doc.version),
    metaRow("Date", doc.date),
    metaRow("Approved By", doc.approvedBy),
    metaRow("Scope", doc.scope),

    // Horizontal rule after metadata
    new Paragraph({
      children: [],
      spacing: { before: 100, after: 100 },
      border: { bottom: { style: BorderStyle.SINGLE, size: 2, color: BRAND_COLOR, space: 4 } },
    }),

    // Disclaimer
    new Paragraph({
      children: [
        new TextRun({
          text: "This document is an AI-assisted draft generated by PinkPepper. It must be reviewed and validated by a qualified person before operational use.",
          italics: true,
          size: 18,
          color: GRAY_COLOR,
        }),
      ],
      spacing: { before: 100, after: 200 },
    }),
  ];

  for (let si = 0; si < doc.sections.length; si++) {
    const section = doc.sections[si];
    children.push(
      new Paragraph({
        text: `${si + 1}. ${section.heading}`,
        heading: HeadingLevel.HEADING_1,
        spacing: { before: 300, after: 120 },
      })
    );

    for (const line of section.content.split("\n")) {
      children.push(
        new Paragraph({
          children: [new TextRun({ text: line, size: 22 })],
          spacing: { after: 100 },
        })
      );
    }

    if (section.subsections) {
      for (let ssi = 0; ssi < section.subsections.length; ssi++) {
        const sub = section.subsections[ssi];
        children.push(
          new Paragraph({
            text: `${si + 1}.${ssi + 1} ${sub.heading}`,
            heading: HeadingLevel.HEADING_2,
            spacing: { before: 200, after: 100 },
          })
        );
        for (const line of sub.content.split("\n")) {
          children.push(
            new Paragraph({
              children: [new TextRun({ text: line, size: 22 })],
              spacing: { after: 80 },
            })
          );
        }
      }
    }
  }

  if (doc.tables) {
    for (const table of doc.tables) {
      if (table.caption) {
        children.push(
          new Paragraph({
            children: [new TextRun({ text: table.caption, bold: true, size: 22 })],
            spacing: { before: 200, after: 80 },
          })
        );
      }
      children.push(renderTable(table));
      children.push(new Paragraph({ text: "", spacing: { after: 120 } }));
    }
  }

  const document = new Document({
    styles: {
      paragraphStyles: [
        {
          id: "Title",
          name: "Title",
          run: { color: BRAND_COLOR, bold: true, size: 48 },
        },
      ],
    },
    sections: [
      {
        properties: {
          page: {
            size: { width: 11906, height: 16838 }, // A4 in twips
            margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 }, // 1 inch margins
          },
        },
        headers: {
          default: new Header({
            children: [
              new Paragraph({
                children: headerChildren,
              }),
            ],
          }),
        },
        footers: {
          default: new Footer({
            children: [
              new Paragraph({
                alignment: AlignmentType.CENTER,
                border: { top: { style: BorderStyle.SINGLE, size: 1, color: "E2E8F0", space: 4 } },
                children: [
                  new TextRun({ text: "Generated by PinkPepper — AI-assisted draft  •  Page ", size: 16, color: GRAY_COLOR }),
                  new TextRun({ children: [PageNumber.CURRENT], size: 16, color: GRAY_COLOR }),
                  new TextRun({ text: " of ", size: 16, color: GRAY_COLOR }),
                  new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 16, color: GRAY_COLOR }),
                ],
              }),
            ],
          }),
        },
        children,
      },
    ],
  });

  const buffer = await Packer.toBuffer(document);
  return buffer.buffer.slice(buffer.byteOffset, buffer.byteOffset + buffer.byteLength) as ArrayBuffer;
}
