import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { NextResponse } from "next/server";
import {
  canExportPdf,
  getExportContext,
  getLatestAssistantMessageForConversation,
  recordExportUsage,
} from "@/lib/export/common";
import { exportLimiter, checkRateLimit } from "@/lib/ratelimit";
import { renderPdf } from "@/lib/documents/render-pdf";
import type { GeneratedDocument } from "@/lib/documents/types";

export const dynamic = "force-dynamic";

const BRAND = rgb(0.882, 0.114, 0.282); // #E11D48
const GRAY = rgb(0.392, 0.455, 0.545);

function wrapText(text: string, maxLineLength = 95) {
  const words = text.replace(/\r\n/g, "\n").split(/\s+/);
  const lines: string[] = [];
  let current = "";

  for (const word of words) {
    if (!word) continue;
    if ((current + " " + word).trim().length > maxLineLength) {
      lines.push(current.trim());
      current = word;
    } else {
      current = `${current} ${word}`.trim();
    }
  }

  if (current.trim()) lines.push(current.trim());
  return lines;
}

export async function POST(request: Request) {
  try {
    const { supabase, userId, tier, isAdmin } = await getExportContext();

    const rateLimitRes = await checkRateLimit(exportLimiter, userId);
    if (rateLimitRes) return rateLimitRes;

    if (!canExportPdf(tier, isAdmin)) {
      return NextResponse.json({ error: "PDF export is not available for your plan." }, { status: 403 });
    }

    const body = (await request.json()) as { conversationId?: string };
    const conversationId = body.conversationId?.trim();
    if (!conversationId || conversationId.length > 128) {
      return NextResponse.json({ error: "A valid conversationId is required." }, { status: 400 });
    }

    const docData = await getLatestAssistantMessageForConversation({
      supabase,
      userId,
      conversationId,
    });

    // Try to use the structured renderer if a generated document is stored in metadata
    const generatedDoc = (docData.metadata as Record<string, unknown> | null)?.generatedDocument as GeneratedDocument | undefined;

    let bytes: Uint8Array;

    if (generatedDoc?.documentType && generatedDoc?.sections) {
      // Use the professional structured renderer
      bytes = await renderPdf(generatedDoc);
    } else {
      // Fallback: render chat content with branded header/footer
      const pdfDoc = await PDFDocument.create();
      const page = pdfDoc.addPage([595.28, 841.89]);
      const font = await pdfDoc.embedFont(StandardFonts.Helvetica);
      const bold = await pdfDoc.embedFont(StandardFonts.HelveticaBold);

      // Header bar with logo
      const headerH = 60;
      page.drawRectangle({ x: 0, y: 841.89 - headerH, width: 595.28, height: headerH, color: BRAND });
      let logoEmbedded = false;
      try {
        const logoPath = join(process.cwd(), "public", "LogoV3.png");
        const logoBytes = await readFile(logoPath);
        const logoImage = await pdfDoc.embedPng(logoBytes);
        const logoDims = logoImage.scale(1);
        const logoH = 32;
        const logoW = (logoDims.width / logoDims.height) * logoH;
        page.drawImage(logoImage, {
          x: 40,
          y: 841.89 - headerH + (headerH - logoH) / 2,
          width: logoW,
          height: logoH,
        });
        page.drawText("Food Safety Compliance", {
          x: 40 + logoW + 12,
          y: 841.89 - headerH + (headerH - 10) / 2,
          size: 10, font, color: rgb(1, 1, 1),
        });
        logoEmbedded = true;
      } catch { /* logo not available */ }
      if (!logoEmbedded) {
        page.drawText("PinkPepper", { x: 40, y: 841.89 - 38, size: 18, font: bold, color: rgb(1, 1, 1) });
        page.drawText("Food Safety Compliance", { x: 40, y: 841.89 - 52, size: 10, font, color: rgb(1, 1, 1) });
      }

      let y = 760;

      page.drawText(docData.conversationTitle, {
        x: 40,
        y,
        size: 16,
        font: bold,
        color: rgb(0.17, 0.17, 0.17),
      });

      y -= 24;
      page.drawText(`Generated: ${new Date().toISOString()}`, { x: 40, y, size: 10, font, color: GRAY });
      y -= 16;
      page.drawText("AI-assisted draft — human validation required before operational use.", {
        x: 40,
        y,
        size: 9,
        font,
        color: GRAY,
      });

      y -= 24;

      const lines = wrapText(docData.content, 96);
      let currentPage = page;
      for (const line of lines) {
        if (y < 40) {
          currentPage = pdfDoc.addPage([595.28, 841.89]);
          y = 800;
        }
        currentPage.drawText(line, { x: 40, y, size: 11, font, color: rgb(0.17, 0.17, 0.17) });
        y -= 14;
      }

      // Footer on each page
      const pages = pdfDoc.getPages();
      pages.forEach((p, idx) => {
        p.drawText(`Generated by PinkPepper • Page ${idx + 1} of ${pages.length}`, {
          x: 40,
          y: 20,
          size: 8,
          font,
          color: GRAY,
        });
      });

      bytes = await pdfDoc.save();
    }

    await recordExportUsage({ supabase, userId, format: "pdf", conversationId });

    const safeId = conversationId.replace(/[^\w-]/g, "_").substring(0, 64);
    const fileName = `pinkpepper-${safeId}.pdf`;

    return new NextResponse(Buffer.from(bytes), {
      headers: {
        "Content-Type": "application/pdf",
        "Content-Disposition": `attachment; filename="${fileName}"`,
      },
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Export failed";
    if (message === "UNAUTHORIZED") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    if (message === "CONVERSATION_NOT_FOUND") {
      return NextResponse.json({ error: "Conversation not found." }, { status: 404 });
    }
    if (message === "NO_ASSISTANT_CONTENT") {
      return NextResponse.json({ error: "No assistant response available to export." }, { status: 400 });
    }
    console.error("[export/pdf] unhandled error:", error);
    return NextResponse.json({ error: "Export failed. Please try again." }, { status: 500 });
  }
}
