import { Document, Packer, Paragraph, TextRun, ImageRun, HeadingLevel, Header, Footer, AlignmentType, PageNumber, BorderStyle } from "docx";
import { readFile } from "node:fs/promises";
import { join } from "node:path";
import { NextResponse } from "next/server";
import {
  canExportDocx,
  getExportContext,
  getLatestAssistantMessageForConversation,
  recordExportUsage,
} from "@/lib/export/common";
import { exportLimiter, checkRateLimit } from "@/lib/ratelimit";
import { renderDocx } from "@/lib/documents/render-docx";
import type { GeneratedDocument } from "@/lib/documents/types";

export const dynamic = "force-dynamic";

const BRAND_COLOR = "E11D48";
const GRAY_COLOR = "64748B";

export async function POST(request: Request) {
  try {
    const { supabase, userId, tier, isAdmin } = await getExportContext();

    const rateLimitRes = await checkRateLimit(exportLimiter, userId);
    if (rateLimitRes) return rateLimitRes;

    if (!canExportDocx(tier, isAdmin)) {
      return NextResponse.json({ error: "DOCX export is only available on Pro." }, { status: 403 });
    }

    const body = (await request.json()) as { conversationId?: string };
    const conversationId = body.conversationId?.trim();
    if (!conversationId || conversationId.length > 128) {
      return NextResponse.json({ error: "A valid conversationId is required." }, { status: 400 });
    }

    const docData = await getLatestAssistantMessageForConversation({
      supabase,
      userId,
      conversationId,
    });

    // Try to use the structured renderer if a generated document is stored in metadata
    const generatedDoc = (docData.metadata as Record<string, unknown> | null)?.generatedDocument as GeneratedDocument | undefined;

    let bodyBytes: Uint8Array;

    if (generatedDoc?.documentType && generatedDoc?.sections) {
      // Use the professional structured renderer
      const buffer = await renderDocx(generatedDoc);
      bodyBytes = new Uint8Array(buffer);
    } else {
      // Fallback: render chat content with branded header/footer
      const paragraphs = docData.content
        .replace(/\r\n/g, "\n")
        .split("\n")
        .filter((line: string) => line.trim().length > 0)
        .map(
          (line: string) =>
            new Paragraph({
              children: [new TextRun({ text: line, size: 22 })],
              spacing: { after: 160 },
            })
        );

      // Build header with logo or text fallback
      const headerItems: (TextRun | ImageRun)[] = [];
      try {
        const logoPath = join(process.cwd(), "public", "LogoV3.png");
        const logoBuffer = await readFile(logoPath);
        headerItems.push(
          new ImageRun({ data: logoBuffer, transformation: { width: 120, height: 32 }, type: "png" })
        );
        headerItems.push(
          new TextRun({ text: "  |  Food Safety Compliance", color: GRAY_COLOR, size: 16 })
        );
      } catch {
        headerItems.push(
          new TextRun({ text: "PinkPepper", bold: true, color: BRAND_COLOR, size: 20 })
        );
        headerItems.push(
          new TextRun({ text: "  |  Food Safety Compliance", color: GRAY_COLOR, size: 16 })
        );
      }

      const doc = new Document({
        sections: [
          {
            properties: {
              page: {
                size: { width: 11906, height: 16838 },
                margin: { top: 1440, bottom: 1440, left: 1440, right: 1440 },
              },
            },
            headers: {
              default: new Header({
                children: [
                  new Paragraph({ children: headerItems }),
                ],
              }),
            },
            footers: {
              default: new Footer({
                children: [
                  new Paragraph({
                    alignment: AlignmentType.CENTER,
                    border: { top: { style: BorderStyle.SINGLE, size: 1, color: "E2E8F0", space: 4 } },
                    children: [
                      new TextRun({ text: "Generated by PinkPepper — AI-assisted draft  •  Page ", size: 16, color: GRAY_COLOR }),
                      new TextRun({ children: [PageNumber.CURRENT], size: 16, color: GRAY_COLOR }),
                      new TextRun({ text: " of ", size: 16, color: GRAY_COLOR }),
                      new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 16, color: GRAY_COLOR }),
                    ],
                  }),
                ],
              }),
            },
            children: [
              new Paragraph({
                heading: HeadingLevel.HEADING_1,
                children: [new TextRun({ text: docData.conversationTitle, bold: true, color: BRAND_COLOR, size: 48 })],
                spacing: { after: 200 },
              }),
              new Paragraph({ children: [new TextRun(`Generated: ${new Date().toISOString()}`)] }),
              new Paragraph({
                children: [new TextRun({
                  text: "This is an AI-assisted draft. Human validation is required before operational use.",
                  italics: true,
                  color: GRAY_COLOR,
                  size: 18,
                })],
                spacing: { after: 200 },
              }),
              ...paragraphs,
            ],
          },
        ],
      });

      const buffer = await Packer.toBuffer(doc);
      bodyBytes = new Uint8Array(buffer);
    }

    await recordExportUsage({ supabase, userId, format: "docx", conversationId });

    const safeId = conversationId.replace(/[^\w-]/g, "_").substring(0, 64);
    const fileName = `pinkpepper-${safeId}.docx`;

    return new NextResponse(Buffer.from(bodyBytes), {
      headers: {
        "Content-Type": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        "Content-Disposition": `attachment; filename="${fileName}"`,
      },
    });
  } catch (error) {
    const message = error instanceof Error ? error.message : "Export failed";
    if (message === "UNAUTHORIZED") {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }
    if (message === "CONVERSATION_NOT_FOUND") {
      return NextResponse.json({ error: "Conversation not found." }, { status: 404 });
    }
    if (message === "NO_ASSISTANT_CONTENT") {
      return NextResponse.json({ error: "No assistant response available to export." }, { status: 400 });
    }
    console.error("[export/docx] unhandled error:", error);
    return NextResponse.json({ error: "Export failed. Please try again." }, { status: 500 });
  }
}
